### ISSUE TITLE
GROMACS host requirement is breaking macOS CI

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/sire#193]
I'm not 100% sure if this is the cause, but I'm seeing repeated failures in the environment setup stage for my `sire-emle` build on macOS. In the log I see:

```
/Users/runner/miniconda3/envs/sire_build/conda-bld/sire_1714379289268/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/etc/conda/activate.d/gromacs_activate.sh: line 22: /Users/runner/miniconda3/envs/sire_build/conda-bld/sire_1714379289268/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin.SSE2/GMXRC: No such file or directory
Traceback (most recent call last):
source tree in: /Users/runner/miniconda3/envs/sire_build/conda-bld/sire_1714379289268/work
  File "/Users/runner/miniconda3/envs/sire_build/bin/conda-mambabuild", line 10, in <module>
export PREFIX=/Users/runner/miniconda3/envs/sire_build/conda-bld/sire_1714379289268/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
export BUILD_PREFIX=/Users/runner/miniconda3/envs/sire_build/conda-bld/sire_1714379289268/_build_env
export SRC_DIR=/Users/runner/miniconda3/envs/sire_build/conda-bld/sire_1714379289268/work
    sys.exit(main())
  File "/Users/runner/miniconda3/envs/sire_build/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 301, in main
    call_conda_build(action, config)
  File "/Users/runner/miniconda3/envs/sire_build/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 273, in call_conda_build
    result = api.build(
  File "/Users/runner/miniconda3/envs/sire_build/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
    return build_tree(
  File "/Users/runner/miniconda3/envs/sire_build/lib/python3.10/site-packages/conda_build/build.py", line 3762, in build_tree
    packages_from_this = build(
  File "/Users/runner/miniconda3/envs/sire_build/lib/python3.10/site-packages/conda_build/build.py", line 2634, in build
    utils.check_call_env(
  File "/Users/runner/miniconda3/envs/sire_build/lib/python3.10/site-packages/conda_build/utils.py", line 408, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "/Users/runner/miniconda3/envs/sire_build/lib/python3.10/site-packages/conda_build/utils.py", line 384, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/runner/miniconda3/envs/sire_build/conda-bld/sire_1714379289268/work/conda_build.sh']' returned non-zero exit status 1.
```

In particular, not the:

```
... /bin.SSE2/GMXRC: No such file or directory
```

The versions of GROMACS barely differs to the last working build:

_works_:
```
    gromacs:                       2023.4-nompi_h9dceb8e_102            conda-forge
```

_fails_:
```
    gromacs:                       2023.4-nompi_hf1d43a3_102              conda-forge
```

I've removed `gromacs` from the requirements and it works completely fine. I'm really puzzled by this since there haven't been any recent merges on their [feedstock](https://github.com/conda-forge/gromacs-feedstock/pulls?q=is%3Apr+is%3Aclosed). (Last was March 28th.)

**Comment by lohedges** [comment]
Okay, this is because we are now using macOS ARM runners. According to the [table](https://github.com/actions/runner-images?tab=readme-ov-file#available-images) the only intel-based macOS-14 runner is macos-14-large. @chryswoods: We should probably update our CI accordingly.

**Comment by chryswoods** [comment]
Cool - I knew the arm runners were coming but hadn't realised they are now here. I'll update the workflows once I get some time (likely later this week)

**Comment by lohedges** [comment]
One nice thing is that the macOS arm64 runners are _really_ fast. It takes just shy of an hour for a build.

**Comment by lohedges** [comment]
Closing since the problematic GROMACS conda package has been rebuilt.
