### ISSUE TITLE
[BUG] somd-freenrg.py fails with "Periodic box vectors must be in reduced form"

### ISSUE THREAD

**Issue by nigel-palmer-cresset** [OpenBioSim/sire#197]
**Describe the bug**

Hi, the following error is raised with somd-freenrg.py with Sire 2024.1.0. Do you know what I am doing wrong?

```
"/data/tmp/nigel.palmer/ceb3/conan/p/sireb703ab24f536d/p/bin/sire_python" --ignore-ipython "/data/tmp/nigel.palmer/ceb3/conan/p/sireb703ab24f536d/p/share/Sire/scripts/somd-freenrg.py" -C Config.cfg
Starting /data/tmp/nigel.palmer/ceb3/conan/p/sireb703ab24f536d/p/bin/sire_python: number of threads equals 6
OPENMM_PLUGIN_DIR = /data/tmp/nigel.palmer/ceb3/conan/p/sireb703ab24f536d/p/lib/plugins

Loading configuration information from file Config.cfg

Running a somd-freenrg calculation using files Input.prm7, Input.rst7 and Input.pert.
Using parameters:
===============
barostat == True
buffered coordinates frequency == 1250
center solute == True
charge difference == 0
constraint == hbonds-notperturbed
coulomb power == 1
crdfile == Input.rst7
cutoff distance == 9 Å
cutoff type == PME
energy frequency == 250
equilibrate == True
equilibration iterations == 5000
gpu == 0
hydrogen mass repartitioning factor == 1.5
integrator == langevinmiddle
lambda array == (0.0, 0.0078, 0.0156, 0.0234, 0.0313, 0.0391, 0.0469, 0.0547, 0.0625, 0.0703, 0.0781, 0.0859, 0.0938, 0.1016, 0.1094, 0.1172, 0.125, 0.1328, 0.1406, 0.1484, 0.1563, 0.1641, 0.1719, 0.1797, 0.1875, 0.1953, 0.2031, 0.2109, 0.2188, 0.2266, 0.2344, 0.2422, 0.25, 0.2578, 0.2656, 0.2734, 0.2813, 0.2891, 0.2969, 0.3047, 0.3125, 0.3203, 0.3281, 0.3359, 0.3438, 0.3516, 0.3594, 0.3672, 0.375, 0.3828, 0.3906, 0.3984, 0.4063, 0.4141, 0.4219, 0.4297, 0.4375, 0.4453, 0.4531, 0.4609, 0.4688, 0.4766, 0.4844, 0.4922, 0.5, 0.5078, 0.5156, 0.5234, 0.5313, 0.5391, 0.5469, 0.5547, 0.5625, 0.5703, 0.5781, 0.5859, 0.5938, 0.6016, 0.6094, 0.6172, 0.625, 0.6328, 0.6406, 0.6484, 0.6563, 0.6641, 0.6719, 0.6797, 0.6875, 0.6953, 0.7031, 0.7109, 0.7188, 0.7266, 0.7344, 0.7422, 0.75, 0.7578, 0.7656, 0.7734, 0.7813, 0.7891, 0.7969, 0.8047, 0.8125, 0.8203, 0.8281, 0.8359, 0.8438, 0.8516, 0.8594, 0.8672, 0.875, 0.8828, 0.8906, 0.8984, 0.9063, 0.9141, 0.9219, 0.9297, 0.9375, 0.9453, 0.9531, 0.9609, 0.9688, 0.9766, 0.9844, 0.9922, 1.0)
lambda_val == 0.125
minimal coordinate saving == False
minimise == False
morphfile == Input.pert
ncycles == 10
nmoves == 5000
perturbed residue number == 986
platform == CUDA
precision == mixed
pressure == 1.01325e-26 g Å-1 ps-2
reaction field dielectric == 82.0
save coordinates == True
shift delta == 1.0
temperature == 298 K
thermostat == False
timestep == 0.001 ps
topfile == Input.prm7
===============
### Running Single Topology Molecular Dynamics Free Energy (v0.2) on cressgpu6 ###
###================Setting up calculation=====================###
New run. Loading input and creating restart
lambda is 0.125
Create the System...
Selecting dummy groups
Applying Hydrogen Mass repartition to input using a factor of 1.5 
Creating force fields... 
The difference in charge is 0
Setting up moves...
Created one MD move that uses OpenMM for all molecules on GPU device 0
Saving restart
Setting up sim file. 
There are 2994 atoms in the group 
###===========================================================###

Traceback (most recent call last):
  File "/data/tmp/nigel.palmer/ceb3/conan/p/sireb703ab24f536d/p/share/Sire/scripts/somd-freenrg.py", line 225, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/data/tmp/nigel.palmer/ceb3/conan/p/sireb703ab24f536d/p/lib/python3.11/site-packages/sire/legacy/Tools/__init__.py", line 175, in inner
    retval = func()
             ^^^^^^
  File "/data/tmp/nigel.palmer/ceb3/conan/p/sireb703ab24f536d/p/lib/python3.11/site-packages/sire/legacy/Tools/OpenMMMD.py", line 2959, in runFreeNrg
    print(f"Initial energy: {integrator.getPotentialEnergy(system)}")
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Periodic box vectors must be in reduced form.`
```

**To Reproduce**

The input and config files are at [PeriodicBoxError.zip](https://github.com/OpenBioSim/sire/files/15345699/PeriodicBoxError.zip)

The command was `"bin/sire_python" --ignore-ipython "share/Sire/scripts/somd-freenrg.py" -C Config.cfg`

**(please complete the following information):**
 - OS: AlmaLinux release 8.9 (Midnight Oncilla)
 - Version of Python: 3.11
 - Version of sire: 2024.1.0
 - The `Input.pert` file was generated with BioSimSpace  2024.1.0
 - I confirm that I have checked this bug still exists in the latest released version of sire: no

**Additional context**
https://github.com/OpenBioSim/sire/issues/159 looks to be similar

**Comment by lohedges** [comment]
You can also use the `reduce_box` and `rotate_box` keyword arguments when reading molecules, i.e.:

```python
import BioSimSpace as BSS

system = BSS.IO.readMolecules(["Input.prm7", "Input.rst7"], reduce_box=True, rotate_box=True)
```

**Comment by nigel-palmer-cresset** [comment]
Hi @lohedges, I was using https://github.com/OpenBioSim/biosimspace/blob/devel/nodes/playground/prepareFEP.py.
Does this mean `merged.reduceBoxVectors()` need to be called before the `BSS.IO.saveMolecules` call on line 272?

**Comment by lohedges** [comment]
Ah, I see. Yes, that should be added there. I'll do that along with the the fix for the other issue that you reported [here](https://github.com/OpenBioSim/biosimspace/issues/291). OpenMM always expects things to be in reduced form and checks this to numerical precision, i.e. you probably want to re-reduce even if they are in reduced form already.

**Comment by nigel-palmer-cresset** [comment]
Ok, thanks for the help
