### ISSUE TITLE
[BUG] rhombic dodecahedron triclinic spaces not working with OpenMM

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/sire#56]
The rhombic dodecahedron box parameters generated by Sire/BioSimSpace are not working with OpenMM. This is true both before and after the rounding fix introduces in #51. Internally OpenMM uses the same lattice reduction as us (it checks for reduced box dimensions), so I'm surprised this is not working. Other engines are fine with the parameters. Hopefully it's possible to apply a specific fix for this box type.

```python
In [1]: import BioSimSpace as BSS

In [2]: mol = BSS.Parameters.openff_unconstrained_2_0_0("C").getMolecule()

In [3]: box, angles = BSS.Box.rhombicDodecahedronHexagon(3*BSS.Units.Length.nanometer)

In [4]: solvated = BSS.Solvent.tip3p(mol, box=box, angles=angles)

In [5]: p = BSS.Protocol.Minimisation(steps=1000)

In [6]: process = BSS.Process.OpenMM(solvated, p)

In [7]: process.start()
Out[7]: BioSimSpace.Process.OpenMM(<BioSimSpace.System: nMolecules=622>, BioSimSpace.Protocol.Minimisation(steps=1000, restraint=None, force_constant=10.0 kcal_per_mol/angstrom**2), exe='/home/lester/.conda/envs/openbiosim/bin/sire_python', name='openmm', platform='CPU', work_dir='/tmp/tmpijqr1ske', seed=None)

In [8]: process.wait()

In [9]: process.isError()
Out[9]: True

In [10]: process.stderr()
/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Traceback (most recent call last):
  File "/tmp/tmpijqr1ske/openmm_script.py", line 34, in <module>
    simulation = Simulation(prmtop.topology,
  File "/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/openmm.py", line 10069, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: NonbondedForce: The cutoff distance cannot be greater than half the periodic box size.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#boxsize

In [11]: box, angles = BSS.Box.rhombicDodecahedronSquare(3*BSS.Units.Length.nanometer)

In [12]: solvated = BSS.Solvent.tip3p(mol, box=box, angles=angles)

In [13]: process = BSS.Process.OpenMM(solvated, p)

In [14]: process.start()
Out[14]: BioSimSpace.Process.OpenMM(<BioSimSpace.System: nMolecules=632>, BioSimSpace.Protocol.Minimisation(steps=1000, restraint=None, force_constant=10.0 kcal_per_mol/angstrom**2), exe='/home/lester/.conda/envs/openbiosim/bin/sire_python', name='openmm', platform='CPU', work_dir='/tmp/tmpmd9xk4t6', seed=None)

In [15]: process.wait()

In [16]: process.isError()
Out[16]: True

In [17]: process.stderr()
Traceback (most recent call last):
  File "/tmp/tmpmd9xk4t6/openmm_script.py", line 16, in <module>
    prmtop = AmberPrmtopFile('openmm.prm7')
  File "/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/app/amberprmtopfile.py", line 156, in __init__
    top.setPeriodicBoxVectors(computePeriodicBoxVectors(*(box[1:4] + box[0:1]*3)))
  File "/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/app/internal/unitcell.py", line 60, in computePeriodicBoxVectors
    cz = math.sqrt(c_length*c_length-cx*cx-cy*cy)
ValueError: math domain error
```

In both cases the box dimensions and angles are stable, and are the same before/after the fix, i.e.:

```python
In [1]: import BioSimSpace as BSS

In [2]: box, angles = BSS.Box.rhombicDodecahedronHexagon(3*BSS.Units.Length.nanometer)

In [3]: mol = BSS.Parameters.openff_unconstrained_2_0_0("C").getMolecule()

In [4]: solvated = BSS.Solvent.tip3p(mol, box=box, angles=angles)

In [5]: solvated.getBox()
Out[5]:
([30.0000 A, 25.9856 A, 30.0000 A],
 [73.7993 degrees, 120.0000 degrees, 88.8975 degrees])

In [6]: box, angles = BSS.Box.rhombicDodecahedronSquare(3*BSS.Units.Length.nanometer)

In [7]: solvated = BSS.Solvent.tip3p(mol, box=box, angles=angles)

In [8]: solvated.getBox()
Out[8]:
([30.0000 A, 30.0000 A, 30.0000 A],
 [120.0000 degrees, 120.0000 degrees, 90.0000 degrees])
```

**Comment by lohedges** [comment]
I'm not sure what's going on here, but it looks like an OpenMM issue. Here is the region of code that where the AMBER format input (box dimensions and angles) is converted to lattice vectors:

```python
def computePeriodicBoxVectors(a_length, b_length, c_length, alpha, beta, gamma):
    """Convert lengths and angles to periodic box vectors.

    Lengths should be given in nanometers and angles in radians (or as Quantity
    instances)
    """

    if is_quantity(a_length): a_length = a_length.value_in_unit(nanometers)
    if is_quantity(b_length): b_length = b_length.value_in_unit(nanometers)
    if is_quantity(c_length): c_length = c_length.value_in_unit(nanometers)
    if is_quantity(alpha): alpha = alpha.value_in_unit(radians)
    if is_quantity(beta): beta = beta.value_in_unit(radians)
    if is_quantity(gamma): gamma = gamma.value_in_unit(radians)

    # My debugging    
    print("#alpha            #beta             #gamma")
    print(alpha, beta, gamma)

    # Compute the vectors

    a = [a_length, 0, 0]
    b = [b_length*math.cos(gamma), b_length*math.sin(gamma), 0]
    print(a)
    print(b)
    cx = c_length*math.cos(beta)
    cy = c_length*(math.cos(alpha)-math.cos(beta)*math.cos(gamma))/math.sin(gamma)
    cz = math.sqrt(c_length*c_length-cx*cx-cy*cy)
    c = [cx, cy, cz]

    # If any elements are very close to 0, set them to exactly 0.

    for i in range(3):
        if abs(a[i]) < 1e-6:
            a[i] = 0.0
        if abs(b[i]) < 1e-6:
            b[i] = 0.0
        if abs(c[i]) < 1e-6:
            c[i] = 0.0
    a = Vec3(*a)
    b = Vec3(*b)
    c = Vec3(*c)

    # Make sure they're in the reduced form required by OpenMM.

    c = c - b*round(c[1]/b[1])
    c = c - a*round(c[0]/a[0])
    b = b - a*round(b[0]/a[0])
    return (a, b, c)*nanometers
```

The issue occurs on the line where `cz` is assigned, since the argument to the square root is negative. If I add a print statement to check the angles that are passed in to the function I get the following:

```
#alpha            #beta             #gamma
2.094395224566243 2.094395224566243 2.094395224566243
```

This is completely wrong, since the three angles are different, i.e. at the bottom of the RST7 file:

```
...
  50.0000000  43.3041867  49.9999888  73.5676110 120.0000074  89.3384352
```

Weirdly, if I run the OpenMM script generated by BioSimSpace using a triclinic box type that _does_ work, e.g. a truncated octahedron the I see the following:

```
#alpha            #beta             #gamma
1.2309592434098255 1.2309592434098255 1.2309592434098255
#alpha            #beta             #gamma
1.9106323821810383 1.2309592434098255 1.230959737338004
#alpha            #beta             #gamma
1.2309592434098255 1.2309592434098255 1.2309592434098255
```

Note that only the _second_ line corresponds the the actual angles in the RST7 file. I'll try to work out why this part of the OpenMM code is being called multiple times, and why it is sometimes being passed incorrect box values. Presumably the code that is failing would work if the correct angles are passed in.

Our own code generates the box vectors from angles using the approach from ASE [here](https://github.com/rosswhitfield/ase/blob/5e11b67efbef428a479179de378765ae07c868e4/ase/lattice/triclinic.py#L40-L85), which does work as expected when given the correct angles.

**Comment by lohedges** [comment]
Right, this could is called on reading the file from _any_ format. The issue is that it happens when just loading the PRM7 file, where it is incorrectly generating the box vectors by assuming that this is a cubic box! Here is a minimal example (two line) example to reproduce:

```python
from openmm.app import *

prmtop = AmberPrmtopFile('openmm.prm7')
```

[Here](https://github.com/OpenBioSim/sire/files/11531480/openmm.prm7.txt) is an example PRM7 file containing info for a hexagonal rhombic dodecahedron system. This is the AMBER spec for the `BOX_DIMENSIONS` entry:

```
%FLAG BOX_DIMENSIONS
%FORMAT(5E16.8)  OLDBETA, BOX(1), BOX(2), BOX(3)
  OLDBETA   : periodic box, angle between the XY and YZ planes in
              degrees. This is now redundant, as it is present in the
              inpcrd files. It is ignored here.
  BOX       : the periodic box lengths in the X, Y, and Z directions.
              This is now redundant, as it is present in the inpcrd files.
              It is ignored here.
```

OpenMM appears to be reading this information then applying this as if it was a cubic system, rather than ignoring it and only using the information from the RST7 file.

**Comment by lohedges** [comment]
Annoyingly it's not possible to work around this by simply not writing the `BOX_DIMENSIONS` to the PRM7 file. In this case, you get:

```
Traceback (most recent call last):
  File "/home/lester/Code/openbiosim/biosimspace/demo/tmp/openmm_script.py", line 16, in <module>
    prmtop = AmberPrmtopFile('openmm.prm7')
  File "/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/app/amberprmtopfile.py", line 155, in __init__
    box = prmtop.getBoxBetaAndDimensions()
  File "/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/app/internal/amber_file_parser.py", line 653, in getBoxBetaAndDimensions
    beta=float(self._raw_data["BOX_DIMENSIONS"][0])
KeyError: 'BOX_DIMENSIONS'
```

**Comment by lohedges** [comment]
Unsurprisingly, it works if you replace the `BOX_DIMENSIONS` section in the PRM7 file with information pertaining to an actual cubic box, i.e.:

```
%FLAG BOX_DIMENSIONS
%FORMAT(5E16.8)
  9.00000000E+01  5.00000000E+01  5.00000000E+01  5.00000000E+01
```

I'll report this to OpenMM to see what they say. Looking at the `AmberPrmtopFile` code, it looks like the `computePeriodicBoxVectors` function should only be called when the PRMTOP file contains box information. However, as shown above, there is no way to remove this information from the file without crashing, which would be the easy fix at our end.

**Comment by lohedges** [comment]
> Annoying - am I right that sire isn't affected as we don't read the box info from the prmtop file?

That's right, the values from the prmtop file appear to be ignored on read.

> Does the OpenMM simulation run if we use the new '.dynamics()' code in sire?

I can create the context directly if I use the solvated system from BioSimSpace, for example:

```python
In [1]: import BioSimSpace as BSS

INFO:numexpr.utils:Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
WARNING:root:Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.

In [2]: import sire as sr

In [3]: box, angles = BSS.Box.rhombicDodecahedronHexagon(5*BSS.Units.Length.nanometer)

In [4]: mol = BSS.Parameters.openff_unconstrained_2_0_0("C").getMolecule()

In [5]: solvated = BSS.Solvent.tip3p(mol, box=box, angles=angles)

In [6]: context = sr.convert.to_openmm(sr.system.System(solvated._sire_object))
```

However, going from the AMBER files that I have written gives the following error:

```python
In [7]: s = sr.load("tmp/openmm.*7")

In [8]: context = sr.convert.to_openmm(s)
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/legacy/Convert/__init__.py │
│ :295 in sire_to_openmm                                                                           │
│                                                                                                  │
│   292 │   │   │   platform.setPropertyDefaultValue("UseCpuPme", str(usecpu))                     │
│   293 │   │                                                                                      │
│   294 │   │   try:                                                                               │
│ ❱ 295 │   │   │   context = openmm.Context(system, integrator, platform)                         │
│   296 │   │   except Exception as e:                                                             │
│   297 │   │   │   raise ValueError(                                                              │
│   298 │   │   │   │   "There was a problem creating the OpenMM context. Perhaps "                │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/openmm.py:10069 in       │
│ __init__                                                                                         │
│                                                                                                  │
│   10066 │   │   properties : map< std::string, std::string >                                     │
│   10067 │   │   │   a set of values for platform-specific properties. Keys are the property name │
│   10068 │   │   """                                                                              │
│ ❱ 10069 │   │   _openmm.Context_swiginit(self, _openmm.new_Context(*args))                       │
│   10070 │   │                                                                                    │
│   10071 │   │   self._system = args[0]                                                           │
│   10072 │   │   self._integrator = args[1]                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OpenMMException: NonbondedForce: The cutoff distance cannot be greater than half the periodic box size.  For more information, see
https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#boxsize

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/convert/__init__.py:192 in │
│ to_openmm                                                                                        │
│                                                                                                  │
│   189 │   Convert the passed object from its current object format to an                         │
│   190 │   openmm object format.                                                                  │
│   191 │   """                                                                                    │
│ ❱ 192 │   return sire_to_openmm(to_sire(obj, map=map), map=map)                                  │
│   193                                                                                            │
│   194                                                                                            │
│   195 def biosimspace_to_sire(obj, map=None):                                                    │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/convert/__init__.py:365 in │
│ sire_to_openmm                                                                                   │
│                                                                                                  │
│   362 │                                                                                          │
│   363 │   from ..base import create_map                                                          │
│   364 │                                                                                          │
│ ❱ 365 │   mols = _sire_to_openmm(obj, map=create_map(map))                                       │
│   366 │                                                                                          │
│   367 │   return mols                                                                            │
│   368                                                                                            │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/legacy/Convert/__init__.py │
│ :297 in sire_to_openmm                                                                           │
│                                                                                                  │
│   294 │   │   try:                                                                               │
│   295 │   │   │   context = openmm.Context(system, integrator, platform)                         │
│   296 │   │   except Exception as e:                                                             │
│ ❱ 297 │   │   │   raise ValueError(                                                              │
│   298 │   │   │   │   "There was a problem creating the OpenMM context. Perhaps "                │
│   299 │   │   │   │   "the platform was not supported for this system, options "                 │
│   300 │   │   │   │   f"or on this computer? The error message is: {e}"                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: There was a problem creating the OpenMM context. Perhaps the platform was not supported for this system, options or on this
computer? The error message is: NonbondedForce: The cutoff distance cannot be greater than half the periodic box size.  For more information,
see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#boxsize
```

I'm not sure why this occurs, since both systems have the same space, i.e.:

```python
In [9]: s.property("space")
Out[9]: TriclinicBox( ( 50, 0, 0 ), ( 0.5, 43.3013, 0 ), ( -25, 14.4338, 40.8248 ) )

In [10]: solvated._sire_object.property("space")
Out[10]: TriclinicBox( ( 50, 0, 0 ), ( 0.5, 43.3013, 0 ), ( -25, 14.4338, 40.8248 ) )
```

**Comment by lohedges** [comment]
Sorry, should have added that the files in `tmp` are the ones written for an OpenMM process using the same solvated system.

**Comment by lohedges** [comment]
Reported [here](https://github.com/openmm/openmm/issues/4078).

**Comment by lohedges** [comment]
I'm not sure if these all work, but some options for a workaround until this are fixed are (along with pros/cons):

* Patch the topology file written by `BioSimSpace.Process.OpenMM` so that it contains some fake cubic box parameters. These will be overwritten when we explicitly set the values in the context using those from the RST7 file later in the script. This would mean that we are now writing an invalid topology file, which could be an issue if the user wants to share or re-use for something else afterwards.

* Monkey-patch `AmberPrmtopFile` so that `computePeriodicBoxVectors` isn't called, or is called with some dummy parameters that work. This is easy enough to do and we include some other OpenMM monkey-patches to add additional functionality. It could be an issue if the user modifies the script and `AmberPrmtopFile` is used elsewhere. (Although I'm not sure if the box vectors are actually used anywhere here.)

* Try doing the OpenMM setup using an alternative route, e.g. going via `parmed`, or `opennff`, or even using the native `sire` functionality. However, the `sire` conversion seems to have a similar issue if the system is generated by loading the AMBER files. I'll try these out to see if anything works. I'd rather avoid if possible, since it means that the script is less portable, i.e.  if run outside of our environment, where `openff` and `parmed` might not be needed, or wanted.

**Comment by lohedges** [comment]
Using `parmed` works well and the API is almost identical:

```python
from openmm import *
from openmm.app import *
from openmm.unit import *

import parmed

# Load the topology and coordinate files.
parm = parmed.load_file('openmm.prm7', 'openmm.rst7')

# Initialise the molecular system.
system = parm.createSystem(nonbondedMethod=PME,
                           nonbondedCutoff=1*nanometer,
                           constraints=HBonds)

# Define the integrator.
integrator = LangevinMiddleIntegrator(0*kelvin,
                                1/picosecond,
                                0.002*picoseconds)

# Set the simulation platform.
platform = Platform.getPlatformByName('CPU')
properties = {}

# Initialise and configure the simulation object.
simulation = Simulation(parm.topology,
                        system,
                        integrator,
                        platform,
                        properties)
simulation.context.setPositions(parm.positions)
if parm.box_vectors is not None:
    simulation.context.setPeriodicBoxVectors(*parm.box_vectors)
simulation.minimizeEnergy(maxIterations=1000)
```
